# Generated by Django 4.2.7 on 2023-11-09 16:45
from django.db import migrations
from django_multitenant.db import  migrations as tenant_migrations


class Migration(migrations.Migration):

    dependencies = [
            ('users', '0001_initial'),
        ]
    operations = []
   

    operations += [
        #Distribute tables by their tenant columns. You need to remove constraints before distribution, distribute tables via tenant_migrations.Distribute(), and reinstate the constraints.

        migrations.RunSQL(
            "ALTER TABLE users_account DROP CONSTRAINT users_account_pkey CASCADE;"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE users_classteacher DROP CONSTRAINT users_classteacher_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_country DROP CONSTRAINT users_country_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_director DROP CONSTRAINT users_director_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_headteacher DROP CONSTRAINT users_headteacher_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_level DROP CONSTRAINT users_level_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_schoolworker DROP CONSTRAINT users_schoolworker_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_student DROP CONSTRAINT users_student_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_teacher DROP CONSTRAINT users_teacher_pkey CASCADE;"
        ),
    ]

    operations += [
        tenant_migrations.Distribute("Country", reference=True),
        tenant_migrations.Distribute("Account"),
        tenant_migrations.Distribute("Level"),
        #tenant_migrations.Distribute("UserProfile"),
        tenant_migrations.Distribute("Director"),
        tenant_migrations.Distribute("Headteacher"),
        tenant_migrations.Distribute("ClassTeacher"),
        tenant_migrations.Distribute("Teacher"),
        tenant_migrations.Distribute("SchoolWorker"),
        tenant_migrations.Distribute("Student"),
        
        
    ]

    operations += [
        migrations.RunSQL(
            "ALTER TABLE users_country ADD CONSTRAINT users_country_pkey PRIMARY KEY (id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_account ADD CONSTRAINT users_account_pkey PRIMARY KEY (id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_level ADD CONSTRAINT users_level_pkey PRIMARY KEY (account_id, level_id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_classteacher ADD CONSTRAINT users_classteacher_pkey PRIMARY KEY (account_id, classteacher_id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_director ADD CONSTRAINT users_director_pkey PRIMARY KEY (account_id, director_id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_headteacher ADD CONSTRAINT users_headteacher_pkey PRIMARY KEY (account_id, headteach_id);"
        ),
        
        migrations.RunSQL(
            "ALTER TABLE users_schoolworker ADD CONSTRAINT users_schoolworker_pkey PRIMARY KEY (account_id, schoolworker_id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_student ADD CONSTRAINT users_student_pkey PRIMARY KEY (account_id, student_id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE users_teacher ADD CONSTRAINT users_teacher_pkey PRIMARY KEY (account_id, teacher_id);"
        )
        
    ]
    

   
    