# Generated by Django 4.1.7 on 2023-11-16 18:19

from django.db import migrations
from users.models import *

from django.contrib.auth.models import User
def forwards_func(apps, schema_editor):

    db_alias = schema_editor.connection.alias
    

    user_tr = User.objects.create_user(
        username="turkiye_user", email="turkiye@gmail.com", password="password"
    )

    user_us = User.objects.create_user(
        username="usa_user", email="us@gmail.com", password="password"
    )

    user_fr = User.objects.create_user(
        username="fr_user", email="fr@gmail.com", password="password"
    )

    # Account.objects.using(db_alias).bulk_create(
    #     [
    #         Account.objects.create(
    #             user=user_us,
    #             name="johndoe",
    #             domain_url="domain",
                
    #             country=Country.objects.get(name="Uganda"),
    #         ),
    #         Account(
    #             user=user_us,
    #             name="jilldoe",
    #             domain_url="domain",
              
    #             country=Country.objects.get(name="Uganda"),
    #         ),
    #         Account(
    #             user=user_us,
    #             name="milldoe",
    #             domain_url="domain",
                
    #             country=Country.objects.get(name="Kenya"),
    #         ),
    #         Account(
    #             user=user_tr,
    #             name="alidoe",
    #             domain_url="domain",
                
    #             country=Country.objects.get(name="Uganda"),
    #         ),
    #         Account(
    #             user=user_tr,
    #             name="velidoe",
    #             domain_url="domain",
               
    #             country=Country.objects.get(name="Uganda"),
    #         ),
    #         Account(
    #             user=user_fr,
    #             name="pierredoe",
    #             domain_url="domain",
              
    #             country=Country.objects.get(name="Uganda"),
    #         ),
    #     ]
    # )
    
    # Director.objects.using(db_alias).bulk_create(
    #     [
    #         Director(name="John Doe", account=Account.objects.get(name="johndoe")),
    #         Director(name="Ali Doe", account=Account.objects.get(name="alidoe")),
    #     ]
    # )
def reverse_func(apps, schema_editor):


    Director.objects.all().delete()
    Level.objects.all().delete()
    Teacher.objects.all().delete()
    Account.objects.all().delete()
    Country.objects.all().delete()
    User.objects.get(username="anonymous").delete()
       
    
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_distribute_tables'),
    ]
    operations = [
        
    ]
    operations += [migrations.RunPython(forwards_func, reverse_func )]
