# Generated by Django 4.1.7 on 2023-12-01 19:19

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classteacher',
            name='unique_classteacher_account',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student_account',
        ),
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_teacher_account',
        ),
        migrations.AddField(
            model_name='classteacher',
            name='level',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_class_teacher', to='users.level'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_teacher',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_class_teacher', to='users.classteacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_class', to='users.level'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_teacher', to='users.level'),
        ),
        migrations.AddConstraint(
            model_name='classteacher',
            constraint=models.UniqueConstraint(fields=('classteacher_id', 'account_id', 'email', 'partition_column', 'level_id', 'registration_number', 'username'), name='unique_classteacher_account'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_id', 'account_id', 'role', 'email', 'name', 'partition_column', 'level_id', 'class_teacher_id', 'registration_number', 'username'), name='unique_student_account'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('teacher_id', 'account_id', 'email', 'partition_column', 'name', 'level_id', 'registration_number', 'username'), name='unique_teacher_account'),
        ),
    ]
