# Generated by Django 4.1.13 on 2025-08-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="users.account",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.financecategory",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenues",
                to="users.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="users.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="financereport",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="financereport",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_reports",
                to="users.account",
            ),
        ),
        migrations.AddField(
            model_name="financecategory",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_categories",
                to="users.account",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.financecategory",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="users.account",
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="users.account",
            ),
        ),
    ]
