# Generated by Django 4.2.16 on 2026-08-28 17:49

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.account'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='academic_year',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='finance.academicyear'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.account'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='category',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='finance.financecategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='academic_year',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.academicyear'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.student'),
        ),
        migrations.AddField(
            model_name='financereport',
            name='academic_year',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='finance.academicyear'),
        ),
        migrations.AddField(
            model_name='financereport',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.account'),
        ),
        migrations.AddField(
            model_name='financecategory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='academic_year',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.academicyear'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.financecategory'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.account'),
        ),
        migrations.AddConstraint(
            model_name='financecategory',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_finance_category_per_account'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_academic_year_per_account'),
        ),
    ]
